package com.reindecar.entity.file;

public enum FileUploadType {
    DRIVER_LICENSE_FRONT,
    DRIVER_LICENSE_BACK,
    PASSPORT,
    IDENTITY_CARD,
    VEHICLE_PHOTO,
    INSURANCE_POLICY,
    LICENSE_DOCUMENT,
    HANDOVER_PHOTO,
    HANDOVER_VIDEO,
    RETURN_PHOTO,
    RETURN_VIDEO,
    SIGNED_CONTRACT,
    DAMAGE_PHOTO,
    REPAIR_INVOICE,
    ACCIDENT_REPORT,
    PROFILE_PHOTO,
    OTHER
}
